name: Update RSS Feed

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to trigger it manually via a button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Run script
      run: python aggregate.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/feed.xml
        # If there are no changes, do nothing. If there are, commit them.
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated feed update" && git push)
